// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/book.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookCategory int32

const (
	BookCategory_UNKNOWN    BookCategory = 0
	BookCategory_FICTION    BookCategory = 1
	BookCategory_NONFICTION BookCategory = 2
	BookCategory_SCIFI      BookCategory = 3
	BookCategory_FANTASY    BookCategory = 4
	BookCategory_MYSTERY    BookCategory = 5
	BookCategory_BIOGRAPHY  BookCategory = 6
)

// Enum value maps for BookCategory.
var (
	BookCategory_name = map[int32]string{
		0: "UNKNOWN",
		1: "FICTION",
		2: "NONFICTION",
		3: "SCIFI",
		4: "FANTASY",
		5: "MYSTERY",
		6: "BIOGRAPHY",
	}
	BookCategory_value = map[string]int32{
		"UNKNOWN":    0,
		"FICTION":    1,
		"NONFICTION": 2,
		"SCIFI":      3,
		"FANTASY":    4,
		"MYSTERY":    5,
		"BIOGRAPHY":  6,
	}
)

func (x BookCategory) Enum() *BookCategory {
	p := new(BookCategory)
	*p = x
	return p
}

func (x BookCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_book_proto_enumTypes[0].Descriptor()
}

func (BookCategory) Type() protoreflect.EnumType {
	return &file_proto_book_proto_enumTypes[0]
}

func (x BookCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookCategory.Descriptor instead.
func (BookCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_book_proto_rawDescGZIP(), []int{0}
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	PublishedYear int32                  `protobuf:"varint,7,opt,name=published_year,json=publishedYear,proto3" json:"published_year,omitempty"`
	AuthorId      int32                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"` // Foreign key to Author service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_proto_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_proto_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_proto_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Book) GetPublishedYear() int32 {
	if x != nil {
		return x.PublishedYear
	}
	return 0
}

func (x *Book) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type DetailedBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Category      BookCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=bookstore.BookCategory" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedBook) Reset() {
	*x = DetailedBook{}
	mi := &file_proto_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedBook) ProtoMessage() {}

func (x *DetailedBook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedBook.ProtoReflect.Descriptor instead.
func (*DetailedBook) Descriptor() ([]byte, []int) {
	return file_proto_book_proto_rawDescGZIP(), []int{1}
}

func (x *DetailedBook) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *DetailedBook) GetCategory() BookCategory {
	if x != nil {
		return x.Category
	}
	return BookCategory_UNKNOWN
}

func (x *DetailedBook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetailedBook) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DetailedBook) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_proto_book_proto protoreflect.FileDescriptor

const file_proto_book_proto_rawDesc = "" +
	"\n" +
	"\x10proto/book.proto\x12\tbookstore\"\xc8\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x04 \x01(\tR\x04isbn\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12%\n" +
	"\x0epublished_year\x18\a \x01(\x05R\rpublishedYear\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x05R\bauthorId\"\xb6\x01\n" +
	"\fDetailedBook\x12#\n" +
	"\x04book\x18\x01 \x01(\v2\x0f.bookstore.BookR\x04book\x123\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x17.bookstore.BookCategoryR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating*l\n" +
	"\fBookCategory\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aFICTION\x10\x01\x12\x0e\n" +
	"\n" +
	"NONFICTION\x10\x02\x12\t\n" +
	"\x05SCIFI\x10\x03\x12\v\n" +
	"\aFANTASY\x10\x04\x12\v\n" +
	"\aMYSTERY\x10\x05\x12\r\n" +
	"\tBIOGRAPHY\x10\x06B\x19Z\x17book-catalog-grpc/protob\x06proto3"

var (
	file_proto_book_proto_rawDescOnce sync.Once
	file_proto_book_proto_rawDescData []byte
)

func file_proto_book_proto_rawDescGZIP() []byte {
	file_proto_book_proto_rawDescOnce.Do(func() {
		file_proto_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_book_proto_rawDesc), len(file_proto_book_proto_rawDesc)))
	})
	return file_proto_book_proto_rawDescData
}

var file_proto_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_book_proto_goTypes = []any{
	(BookCategory)(0),    // 0: bookstore.BookCategory
	(*Book)(nil),         // 1: bookstore.Book
	(*DetailedBook)(nil), // 2: bookstore.DetailedBook
}
var file_proto_book_proto_depIdxs = []int32{
	1, // 0: bookstore.DetailedBook.book:type_name -> bookstore.Book
	0, // 1: bookstore.DetailedBook.category:type_name -> bookstore.BookCategory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_book_proto_init() }
func file_proto_book_proto_init() {
	if File_proto_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_book_proto_rawDesc), len(file_proto_book_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_book_proto_goTypes,
		DependencyIndexes: file_proto_book_proto_depIdxs,
		EnumInfos:         file_proto_book_proto_enumTypes,
		MessageInfos:      file_proto_book_proto_msgTypes,
	}.Build()
	File_proto_book_proto = out.File
	file_proto_book_proto_goTypes = nil
	file_proto_book_proto_depIdxs = nil
}
